python run-v2.py \
    --model_name hfl/chinese-macbert-base \
    --num_labels 2 \
    --data_dir data-aug \
    --maxlength 128 \
    --pred_output_dir submissions-aug \
    --output_model_dir finetuned_models/ner_run_aug \
    --epoch 3 \
    --batch_size 16 \
    --kfolds 10 \
    --lr 2e-5 \
    --alpha 0.5 \
    --gamma 1 \
    --perform_testing \