python run-v2.py \
    --model_name hfl/chinese-macbert-base \
    --ner_model_name uer/roberta-base-finetuned-cluener2020-chinese \
    --num_labels 2 \
    --data_dir ./data \
    --maxlength 64 \
    --pred_output_dir ./submissions-ner \
    --output_model_dir ./ner_run_v2 \
    --epoch 3 \
    --batch_size 16 \
    --kfolds 8 \
    --lr 5e-5 \
    --alpha 0.3 \
    --gamma 0.8 \
    --perform_testing \
