python run-v2.py \
    --model_name hfl/chinese-macbert-base \
    --num_labels 2 \
    --data_dir data-aug-large \
    --maxlength 128 \
    --pred_output_dir submissions-aug \
    --output_model_dir finetuned_models/ner_run_aug \
    --epoch 3 \
    --batch_size 16 \
    --kfolds 10 \
    --lr 2e-5 \
    --alpha 0.5 \
    --gamma 1 \
    --perform_testing \
    --single_layer_cls_head \
    --resume_fold_idx 1 \
    --checkpoint finetuned_models/ner_run_aug_single/fold9/checkpoint-5014/pytorch_model.bin \
    --from_another_run