python run.py \
    --model_name uer/roberta-base-word-chinese-cluecorpussmall \
    --num_labels 2 \
    --data_dir data/data-org \
    --maxlength 64 \
    --kfolds 10 \
    --minor_major_ratio 1 \
    --pred_output_dir submissions \
    --output_model_dir finetuned_models/structure \
    --n_fold_used 5 \
    --num_ensemble_models 5 \
    --num_epochs 10 \
    --batch_size 32 \
    --lr 2e-5 \
    --alpha 0.5 \
    --gamma 0. \
    --early_stopping_patience 3 \
    --perform_testing 