python run.py \
    --model_name uer/roberta-base-word-chinese-cluecorpussmall \
    --num_labels 2 \
    --data_dir data/data-org \
    --maxlength 64 \
    --kfolds 10 \
    --pred_output_dir submissions \
    --output_model_dir finetuned_models/word-based-roberta \
    --n_fold_used 5 \
    --num_ensemble_models 5 \
    --num_epochs 10 \
    --batch_size 32 \
    --lr 2e-5 \
    --alpha 1.25 \
    --gamma 0.5   \
    --pooling_mode hybrid \
    --local_loss_param 2e-4 \
    --early_stopping_patience 4 \
    --best_by_f1  \
    --perform_testing 