python run.py \
    --model_name hfl/chinese-macbert-base \
    --num_labels 2 \
    --single_layer_cls_head \
    --data_dir data/data-org \
    --maxlength 64 \
    --kfolds 10 \
    --pred_output_dir submissions \
    --output_model_dir finetuned_models/ensemble \
    --n_fold_used 5 \
    --num_ensemble_models 5 \
    --num_epochs 5 \
    --batch_size 64 \
    --lr 1e-5 \
    --alpha 1 \
    --gamma 2 \
    --local_loss_param 1e-3 \
    --perform_testing \